version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.12'
python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true
